import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync,rmSync,readFileSync,writeFileSync } from 'node:fs';
import { spawn } from 'node:child_process';
import { createServer } from 'node:net';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomBytes } from 'node:crypto';
import { gunzipSync } from 'node:zlib';
import { createDemo } from '../demo/server.js';
import { createBuilder,dockerArgs,jobSpec } from '../demo/builders.js';
import { sha } from '../demo/definition.js';
const config={title:'Claims team workspace',brief:'Review synthetic claims and share guidance.',template:'claims',accent:'teal'};
const unpack=buffer=>{const tar=gunzipSync(buffer),files={};for(let n=0;n<tar.length&&tar[n];){const h=tar.subarray(n,n+512),name=h.subarray(0,100).toString().split('\0')[0],size=parseInt(h.subarray(124,136).toString(),8);files[name]=tar.subarray(n+512,n+512+size).toString();n+=512+Math.ceil(size/512)*512;}return files;};
test('DEMO-001 complete authenticated author/build/collaborate/publish/export flow survives restart',async t=>{
  const directory=mkdtempSync(join(tmpdir(),'pac-demo-')),ownerToken=randomBytes(32).toString('hex');
  const runtime=createDemo({directory,ownerToken,builder:createBuilder('process')});
  await new Promise(r=>runtime.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+runtime.server.address().port;
  t.after(()=>{runtime.server.close();rmSync(directory,{recursive:true,force:true});});
  const call=async(path,body,token=ownerToken)=>{const res=await fetch(base+path,{method:body===undefined?'GET':'POST',headers:{Authorization:'Bearer '+token,...(body===undefined?{}:{'Content-Type':'application/json'})},body:body===undefined?undefined:JSON.stringify(body)});return {status:res.status,data:await res.json()};};
  assert.equal((await call('/api/apps',undefined,'wrong')).status,401);
  const cross=await fetch(base+'/api/apps',{headers:{Authorization:'Bearer '+ownerToken,Origin:'https://evil.example'}});assert.equal(cross.status,403);
  const initialized=await call('/mcp',{jsonrpc:'2.0',id:1,method:'initialize',params:{protocolVersion:'2025-03-26'}});assert.equal(initialized.data.result.protocolVersion,'2025-03-26');
  const tools=await call('/mcp',{jsonrpc:'2.0',id:2,method:'tools/list'});assert.ok(tools.data.result.tools.some(t=>t.name==='create_application'));assert.ok(tools.data.result.tools.some(t=>t.name==='get_assurance'));
  const created=await call('/mcp',{jsonrpc:'2.0',id:3,method:'tools/call',params:{name:'create_application',arguments:config}});const app=JSON.parse(created.data.result.content[0].text),p='/api/apps/'+app.id;
  assert.equal((await call(p+'/publish',{})).status,409);
  assert.equal((await call(p+'/build',{})).status,202);await runtime.store.lastBuild;
  const state=await call(p);assert.equal(state.data.build.status,'ready');assert.match(state.data.build.mode,/no container isolation/);
  const preview=await fetch(base+p+'/preview',{headers:{Authorization:'Bearer '+ownerToken}});assert.match(preview.headers.get('content-security-policy'),/sandbox; default-src 'none'/);assert.match(await preview.text(),/Claims team workspace/);
  const invite=await call(p+'/invite',{label:'Morgan'});const token=new URL(invite.data.url).hash.slice(8);
  const accepted=await call('/api/session',{token});assert.equal(accepted.status,200);assert.equal((await call('/api/session',{token})).status,401);
  const collaborator=runtime.store.tokenSession({kind:'collaborator',label:'Morgan',appId:app.id});
  assert.equal((await call(p+'/binding',{},collaborator)).status,403);
  const other=await call('/api/apps',{...config,title:'Private app'});assert.equal((await call('/api/apps/'+other.data.id,undefined,collaborator)).status,404);
  const attack='<script>fetch("https://evil.example")</script>';
  assert.equal((await call(p+'/documents',{name:'guidance.md',base64:Buffer.from(attack).toString('base64')},collaborator)).status,200);
  assert.equal((await call(p+'/documents',{name:'attack.html',base64:'YWJj'},collaborator)).status,400);
  await call(p+'/comments',{text:'Please review the water claim.'},collaborator);await call(p+'/binding',{});await call(p+'/publish',{});
  const html=await (await fetch(base+p+'/preview?published=1',{headers:{Authorization:'Bearer '+collaborator}})).text();assert.ok(!html.includes('<script>'));assert.match(html,/&lt;script&gt;/);assert.match(html,/CLM-DEMO/);assert.match(html,/Please review/);
  await call(p+'/definition',{config:{...config,title:'Unpublished new name'},revision:1});assert.equal((await call(p+'/definition',{config,revision:1})).status,409);assert.equal((await call(p+'/publish',{})).status,409);
  const frozen=await (await fetch(base+p+'/preview?published=1',{headers:{Authorization:'Bearer '+ownerToken}})).text();assert.match(frozen,/Claims team workspace/);assert.ok(!frozen.includes('Unpublished new name'));
  assert.equal((await call(p+'/export',undefined,collaborator)).status,403);
  const exported=await fetch(base+p+'/export',{headers:{Authorization:'Bearer '+ownerToken}});assert.equal(exported.status,200);const files=unpack(Buffer.from(await exported.arrayBuffer()));
  assert.equal(JSON.parse(files['definition.json']).title,config.title);assert.equal(JSON.parse(files['data.json']).documents[0].base64,Buffer.from(attack).toString('base64'));
  for(const [name,digest] of Object.entries(JSON.parse(files['checksums.json'])))assert.equal(sha(files[name]),digest);
  assert.ok(!JSON.stringify(files).includes(ownerToken));assert.ok(!JSON.stringify(files).includes(collaborator));
  const exportDir=mkdtempSync(join(tmpdir(),'pac-export-'));t.after(()=>rmSync(exportDir,{recursive:true,force:true}));
  for(const name of ['package.json','server.js','index.html','data.json'])writeFileSync(join(exportDir,name),files[name]);
  const portServer=createServer();await new Promise(r=>portServer.listen(0,'127.0.0.1',r));const exportPort=portServer.address().port;await new Promise(r=>portServer.close(r));
  const exportToken=randomBytes(32).toString('hex');const child=spawn(process.execPath,['server.js'],{cwd:exportDir,env:{PATH:process.env.PATH,PORT:String(exportPort),PAC_EXPORT_TOKEN:exportToken},stdio:'pipe'});t.after(()=>child.kill());
  const exportUrl='http://127.0.0.1:'+exportPort;let healthy=false;for(let i=0;i<50;i++){try{healthy=(await fetch(exportUrl+'/health')).ok;if(healthy)break;}catch{}await new Promise(r=>setTimeout(r,20));}assert.ok(healthy,'Exported application starts independently');
  assert.equal((await fetch(exportUrl)).status,401);const standalone=await fetch(exportUrl,{headers:{Authorization:'Basic '+Buffer.from('demo:'+exportToken).toString('base64')}});assert.equal(standalone.status,200);assert.match(await standalone.text(),/Claims team workspace/);
  const bridge=spawn(process.execPath,['demo/mcp-stdio.js'],{cwd:new URL('..',import.meta.url),env:{PATH:process.env.PATH,PAC_MANAGER_URL:base,PAC_MANAGER_TOKEN:ownerToken},stdio:'pipe'});let bridgeOut='';bridge.stdout.on('data',b=>bridgeOut+=b);bridge.stdin.end(JSON.stringify({jsonrpc:'2.0',id:99,method:'tools/list'})+'\n');await new Promise((resolve,reject)=>{bridge.on('error',reject);bridge.on('exit',code=>code===0?resolve():reject(new Error('Bridge failed')));});assert.ok(JSON.parse(bridgeOut).result.tools.some(t=>t.name==='update_assurance'));
  const restored=createDemo({directory,ownerToken,builder:createBuilder('process')});assert.equal(restored.store.state.apps[0].release.number,1);assert.equal(restored.store.state.apps[0].comments.length,1);
  assert.ok(!readFileSync(join(directory,'state.json'),'utf8').includes(collaborator));
});
test('DEMO-003 failed or tampered builds cannot be published',async t=>{
  const directory=mkdtempSync(join(tmpdir(),'pac-fail-'));t.after(()=>rmSync(directory,{recursive:true,force:true}));const p={kind:'owner',label:'Test'};
  const runtime=createDemo({directory,ownerToken:'a'.repeat(64),builder:{mode:'failing test double',build:async()=>{throw new Error('Runtime unavailable');}}});const app=runtime.store.create(p,config);runtime.store.startBuild(p,app.id);await runtime.store.lastBuild;assert.equal(app.build.status,'failed');assert.throws(()=>runtime.store.publish(p,app.id),/Build the current/);
  runtime.store.builder={mode:'tampered test double',build:async()=>({html:'<script>unsafe</script>',htmlDigest:'fake',sourceDigest:'fake'})};runtime.store.startBuild(p,app.id);await runtime.store.lastBuild;assert.equal(app.build.status,'failed');assert.match(app.build.logs.at(-1).text,/verification/);
});
test('DEMO-002 isolation adapters request restrictive execution and fail closed',async()=>{
  const args=dockerArgs('builder:demo','job');for(const flag of ['--network=none','--read-only','--cap-drop=ALL','--pids-limit=32','--pull=never'])assert.ok(args.includes(flag));
  const pod=jobSpec('job','pac-builds','image',config).spec.template.spec;assert.equal(pod.automountServiceAccountToken,false);assert.equal(pod.securityContext.runAsNonRoot,true);assert.equal(pod.containers[0].securityContext.allowPrivilegeEscalation,false);
  assert.throws(()=>createBuilder('silently-fallback'));
});
