export function initGraduation({api,action,$,getApp,getMe,toast,esc}){
  const dialog=document.createElement('dialog');dialog.id='graduation';
  dialog.innerHTML=`<div class="graduation-head"><div><p class="eyebrow">READY FOR THE NEXT ENVIRONMENT</p><h2>Review. Download. Graduate.</h2></div><button id="close-graduation" class="subtle">Close</button></div><p id="assurance-status"></p><div class="report-actions"><select id="report-kind" aria-label="Document"><option value="arb">Architecture Review Board</option><option value="readiness">Systems Readiness</option><option value="bom">Bill of Materials</option></select><a id="report-html" class="button">Download HTML</a><a id="report-md" class="button">Markdown</a><a id="report-json" class="button">Source JSON</a><a id="report-open" class="button" target="_blank" rel="noopener">Open preview ↗</a></div><iframe id="report-preview" title="Generated governance document" sandbox=""></iframe><p class="hint">Generated facts follow the published application automatically. Authored decisions retain their evidence and need re-review after a release change. Document generation is not an approval.</p><details id="assurance-edit"><summary>Edit structured decisions and evidence</summary><p>Claude can maintain these records through MCP. You can also edit JSON here. Managed facts regenerate from the app; changes to managed fields are ignored.</p><textarea id="assurance-json" aria-label="Structured assurance data" spellcheck="false"></textarea><button id="save-assurance">Save structured record</button></details><hr><div class="graduation-head"><div><h2>Publish the code to GitHub.</h2><p>Review source and reports before creating a branch in a configured private repository.</p></div><a id="graduate-archive" class="button">Download full package ↓</a></div><p id="github-config-note"></p><div id="github-controls" class="fields"><label>Destination<select id="github-repository"></select></label><button id="github-prepare">Prepare publication</button></div><section id="github-review" hidden><p id="github-plan-summary"></p><p class="hint">Uploaded documents, discussion notes, claims rows and credentials are excluded. Your application brief and authored assurance prose are included.</p><select id="github-file" aria-label="Review file"></select><pre id="github-content"></pre><label><input id="github-confirm" type="checkbox"> I reviewed these files and approve publishing them to this repository and branch.</label><button id="github-publish">Publish reviewed code ↗</button></section><p id="github-result"></p>`;
  document.body.append(dialog);let record,plan,appId;
  const button=document.createElement('button');button.textContent='Graduate ↗';document.querySelector('.toolbar').append(button);
  const report=()=>{const path='/api/apps/'+appId+'/reports/'+$('report-kind').value;$('report-preview').src=path;$('report-open').href=path;for(const format of ['html','md','json'])$('report-'+format).href=path+'?format='+format+'&download=1';};
  const load=async()=>{const result=await api('apps/'+appId+'/assurance');record=result.record;$('assurance-status').textContent=`Release ${record.release??'not published'} · ${result.completeness.missingOrProposed} decisions unknown or proposed · ${record.stale?'Authored decisions need re-review':'Pending independent review'} · Source ${(record.sourceDigest||'unavailable').slice(0,12)}`;$('assurance-json').value=JSON.stringify(record.data,null,2);report();};
  button.onclick=action(async()=>{appId=getApp().id;const owner=getMe().kind==='owner';$('assurance-edit').hidden=!owner;$('graduate-archive').hidden=!owner||!getApp().release;$('graduate-archive').href='/api/apps/'+appId+'/export';$('github-review').hidden=true;$('github-result').textContent='';$('github-controls').hidden=true;await load();dialog.showModal();
    if(owner){const config=await api('apps/'+appId+'/github-config');$('github-config-note').textContent=config.enabled?config.mode:'GitHub publication is disabled. Configure a server-side token and approved private repositories to enable it.';$('github-controls').hidden=!config.enabled;$('github-repository').innerHTML=config.repositories.map(r=>`<option>${esc(r)}</option>`).join('');}else $('github-config-note').textContent='The workspace owner can publish source code.';
  });
  $('close-graduation').onclick=()=>dialog.close();$('report-kind').onchange=report;
  setInterval(async()=>{if(!dialog.open||document.hidden)return;try{const next=(await api('apps/'+appId+'/assurance')).record;if(next.generatedDigest!==record.generatedDigest||next.recordRevision!==record.recordRevision||next.release!==record.release){report();$('github-review').hidden=true;if($('assurance-edit').open){$('assurance-status').textContent='Application changed. Report preview refreshed. Close and reopen graduation to reload decisions before saving.';}else await load();}}catch(error){toast(error.message);}},2000);
  $('save-assurance').onclick=action(async()=>{await api('apps/'+appId+'/assurance',{revision:record.recordRevision,release:record.release,data:JSON.parse($('assurance-json').value)});await load();$('github-review').hidden=true;toast('Structured decisions saved. Reports regenerated.');});
  $('github-prepare').onclick=action(async()=>{plan=await api('apps/'+appId+'/github-prepare',{repository:$('github-repository').value});$('github-plan-summary').textContent=`${plan.repository} → ${plan.branch} · ${plan.files.length} files · Expires in five minutes · ${plan.digest}`;$('github-file').innerHTML=plan.files.map((f,i)=>`<option value="${i}">${esc(f.path)} · ${f.bytes} bytes</option>`).join('');$('github-content').textContent=plan.files[0].content;$('github-confirm').checked=false;$('github-publish').disabled=false;$('github-review').hidden=false;});
  $('github-file').onchange=()=>{$('github-content').textContent=plan.files[Number($('github-file').value)].content;};
  $('github-publish').onclick=action(async()=>{if(!$('github-confirm').checked)throw new Error('Review the file contents and confirm the destination first.');$('github-publish').disabled=true;try{const result=await api('apps/'+appId+'/github-publish',{id:plan.id,digest:plan.digest});$('github-result').textContent='Published commit '+result.commit+' · ';const link=document.createElement('a');link.href=result.url;link.textContent='Open repository branch ↗';link.target='_blank';link.rel='noopener';$('github-result').append(link);$('github-review').hidden=true;}catch(error){$('github-review').hidden=true;throw new Error(error.message+' Prepare a new publication preview before retrying.');}});
}
