import { escape,sha,effectiveKind } from './definition.js';
import { loadBrand } from './brand.js';
import { serviceCatalog } from './definition.js';
const brand=loadBrand();

// One row per declared envRefs binding: env var, service kind, prod projection, caveat. This is
// where a local-only or substituted binding becomes visible before graduation, not during it --
// see docs/implementation-status.md's services-layer section and store.js's graduation gate.
function serviceBindings(app){
  const envRefs=app.config?.envRefs;
  if(!envRefs)return [];
  return Object.entries(envRefs).map(([envVar,kind])=>({
    envVar,kind,
    projection:serviceCatalog.projectionOf(kind)||'unknown',
    caveat:serviceCatalog.caveatOf(kind)||null,
  }));
}

// Template structure only. Customer examples and their populated content are not bundled.
export const sections={
  arb:[
    ['purpose','Purpose and decision requested'],['scope','Scope and exclusions'],['currentState','Current system state'],['targetState','Target system state'],['stakeholders','Stakeholders and responsibilities including finance owner'],['objectives','Measurable business objectives'],['goals','Architecture goals and tradeoffs'],['constraints','Project constraints'],['classification','Architecture classification and justification'],['overview','Architecture overview'],['logicalView','Logical and functional view'],['dataView','Data ownership classification retention and migration'],['developmentView','Development repositories and ownership'],['deploymentView','Deployment and trust boundaries'],['databaseArtifacts','Database artifacts and capacity'],['applicationArtifacts','Application artifacts and registries'],['interfaces','API and integration reference'],['technology','Technology stack and versions'],['deviations','Standard stack deviations and alternatives'],['emerging','Emerging technologies and exit strategy'],['frontend','Frontend frameworks'],['backend','Backend frameworks'],['security','Security privacy and review checkpoints'],['threatModel','Threat model and mitigations'],['waf','Web application firewall'],['vendorMfa','Third party access and MFA'],['recovery','Disaster recovery architecture RTO RPO and testing'],['infrastructureCost','Infrastructure and recovery costs'],['authoringCost','AI authoring licenses and users'],['runtimeCost','Runtime AI workload and costs'],['risks','Risks and mitigation owners'],['nfr','Nonfunctional requirements'],['decisions','Architecture decisions and deviations'],['meetingNotes','ARB meeting notes'],['openItems','Open items and concerns']
  ],
  readiness:[
    ['introduction','Introduction and release scope'],['systemType','System type'],['description','System description'],['documentation','Documentation references'],['schedule','Implementation and rollback schedule'],['users','Users roles and expected volumes'],['browsers','Browser requirements and verification'],['uptime','Uptime objectives'],['peakUsage','High usage periods'],['vendorContacts','Vendor contacts'],['vendorAgreement','Vendor agreements and legal review'],['vendorTest','Vendor test environments'],['arbReview','Architecture review status'],['dataReview','Data working group review'],['hardware','Hardware and capacity'],['network','Network DNS ports and diagrams'],['applicationServer','Application servers and connectivity tests'],['database','Database requirements and identities'],['monitoring','Monitoring health checks and alerting'],['serviceManagement','Service management change records and CMDB'],['logReview','Application log review and retention'],['fileLifecycle','Archive compression and purge'],['highRisk','High risk classification'],['iam','Authentication authorization and auditing'],['informationRisk','Information risk PCI and personal data'],['serverSecurity','Certificates and vulnerability scans'],['recovery','Recovery tier objectives and test evidence'],['batch','Batch schedules and dependencies'],['performance','Load and performance test evidence'],['qa','Quality assurance evidence'],['support','Support contacts escalation and schedule'],['controls','Balance and control reports'],['dependencies','Dependent applications and projects'],['securityReferences','Security reference material']
  ],
  bom:[
    ['introduction','Inventory scope and snapshot date'],['shared','Shared components ownership consumers and dependencies'],['cloud','Cloud resources and infrastructure source'],['devops','DevOps workloads repositories and registries'],['thirdParty','Third party software versions licenses and support'],['endpoints','Internal and external endpoints'],['secrets','Secret references and purposes only'],['encryption','Key and certificate management'],['storage','Storage databases capacity and retention'],['observability','Logs metrics and health checks'],['permissions','Runtime identities and least privilege permissions'],['vulnerabilities','Exposure vulnerability scans and remediation'],['references','Reference documents and standards']
  ]
};
export const reportTitles={arb:'Architecture Review Board',readiness:'Systems Readiness',bom:'Bill of Materials'};
const recordSchema={type:'object',additionalProperties:false,required:['status','text','owner','evidence'],properties:{status:{enum:['unknown','proposed','documented','not-applicable']},text:{type:'string',maxLength:6000},owner:{type:'string',maxLength:120},evidence:{type:'array',maxItems:12,items:{type:'string',maxLength:500}}}};
export const assuranceSchema={type:'object',additionalProperties:false,required:['arb','readiness','bom','components'],properties:{...Object.fromEntries(Object.entries(sections).map(([kind,list])=>[kind,{type:'object',additionalProperties:false,required:list.map(([key])=>key),properties:Object.fromEntries(list.map(([key])=>[key,recordSchema]))}])),components:{type:'array',maxItems:50,items:{type:'object',additionalProperties:false,required:['id','name','category','version','license','owner','source','dependencies','status'],properties:Object.fromEntries(['id','name','category','version','license','owner','source','dependencies','status'].map(key=>[key,{type:'string',maxLength:500}]))}}}};
const entry=(text='',status='unknown',evidence=[])=>({status,text,owner:'Unassigned',evidence});
export function initialAssurance(){return {...Object.fromEntries(Object.entries(sections).map(([kind,list])=>[kind,Object.fromEntries(list.map(([key])=>[key,entry()]))])),components:[]};}
// Real AI-driven generation (see docs/implementation-status.md) made three ARB/BOM claims
// below false for a "kind"-based artifact: "no generated scripts" (the static tier now embeds
// a real, model-written <script> block for interactive/knowledge kinds), "${c.template} layout"
// (undefined -- template is never set on a kind-based record, dual-accept per definition.js),
// and "arbitrary executable code [is] outside this demo" (an "application"-kind artifact is
// exactly that, by design). Computed once per generatedAssurance() call so the classic
// (template-tier), generated-static (interactive/knowledge) and referenced-app (application)
// cases each get an accurate, kind-specific claim instead of one claim covering all three.
function scriptClaim(c){
  const kind=effectiveKind(c);
  if(kind==='classic')return {layout:`${c.template} template`,executableCode:'Live integrations and arbitrary executable code are outside this demo.',scripts:'no generated executable scripts',permissions:'Preview has no generated executable scripts and cannot make outbound requests.'};
  if(c.tier==='app')return {layout:`AI-generated "${kind}" application (referenced source, not embedded)`,executableCode:`This is an "${kind}"-kind artifact: real, arbitrary server-side code by design, generated from the brief. It runs as a real deployed service once graduated -- see the deployment view and BOM permissions for its trust boundary, not the sandboxed-preview claims that apply to the static tier.`,scripts:'a real referenced application, not a sandboxed preview',permissions:`Deployed as a real service (kind "${kind}"); the deploy-time trust boundary (container isolation, network policy) is recorded at deployment, not here.`};
  return {layout:`AI-generated "${kind}" artifact`,executableCode:`Client-side generated code (real HTML/CSS/JS produced from the brief, kind "${kind}") is in scope; it runs sandboxed with no outbound network access. Live server-side integrations remain outside this demo.`,scripts:'generated client-side scripts, sandboxed (iframe, no allow-same-origin) with all outbound network access blocked (CSP connect-src \'none\', safety-gate rejects fetch/XHR/WebSocket)',permissions:'Preview runs generated client-side scripts in a sandboxed, network-blocked iframe (no outbound requests permitted); Docker build workers disable networking regardless of artifact kind.'};
}
export function generatedAssurance(app){
  const c=app.release?.result.config||app.config,r=app.release?.number||0;
  const claim=scriptClaim(c);
  const fact=text=>({status:'documented',text,owner:'PAC Manager generator',evidence:[`artifact:${app.id}/release/${r}`,`definition:${app.release?.result.sourceDigest||sha(JSON.stringify(c))}`]});
  return {
    arb:{purpose:fact(`Review ${c.title} for bounded internal demonstration. ${c.brief} Formal architecture approval remains pending.`),scope:fact(`${claim.layout}; app-scoped uploads and team notes. ${app.binding?'Synthetic claims bound.':'No claims capability granted.'} ${claim.executableCode}`),targetState:fact(`${c.title}: ${c.brief} Published version ${r||'not available'}; visual accent ${c.accent}.`),overview:fact('Authenticated MCP authoring, trusted controller, ephemeral definition compiler, sandboxed HTML preview, and shared JSON persistence. Graduation produces a standalone read-only Node application.'),logicalView:fact('Controller authorizes artifact access; builder compiles a bounded definition; renderer escapes content; the mock claims provider supplies synthetic fixtures when explicitly bound.'),developmentView:fact(`Application source is a strict JSON definition plus ${effectiveKind(c)==='classic'?'generated trusted HTML':'either AI-generated static source (interactive/knowledge) or a referenced real project (application)'}. Source and a Node server are exportable. The platform uses dependency-free Node.js modules.`),applicationArtifacts:fact(`Standalone server.js, index.html, definition.json, data.json, Dockerfile, evidence.json, assurance.json and generated report views. Source digest ${app.release?.result.sourceDigest||'not yet published'}.`),interfaces:fact('MCP tools author and publish the definition. Controller APIs scope data by application. Graduated app exposes public GET /health and authenticated GET / and /data.json. No live claims API.'),frontend:fact(`${claim.layout} with ${c.accent} accent; ${claim.scripts}.`),backend:fact('Controller and standalone snapshot use Node.js. The graduated runtime requires Node.js >=22; exact target image digest remains unspecified.')},
    readiness:{introduction:fact(`Readiness record for ${c.title}, published release ${r||'none'}. Generation does not certify production readiness.`),systemType:fact('Bounded internal web application; standalone export is read-only.'),description:fact(c.brief),documentation:fact('ARB, readiness and BOM views are generated from assurance.json for this artifact. Exact document data and source digests accompany graduation.'),applicationServer:fact(`Build adapter: ${app.release?.mode||app.build?.mode||'Not built'}. Controller uses a single process. Graduated app uses Node.js >=22.`),database:fact(`${app.documents.length} uploaded documents and ${app.comments.length} discussion notes in the shared single-writer platform JSON store. The standalone package uses a JSON snapshot; no PostgreSQL provisioned.`),iam:fact('Platform owner and app-scoped collaborator sessions. Graduated app requires a newly provisioned Basic Auth token. Enterprise identity and revocation workflows remain unimplemented.'),dependencies:fact(app.binding?'Explicit in-process synthetic claims provider; no live enterprise dependency.':'No claims capability bound.')},
    bom:{introduction:fact(`Operational inventory for ${c.title} release ${r||'unpublished'}. Generated from platform state; not a scanned transitive software SBOM.`),shared:fact('PAC controller, trusted compiler, renderer and JSON persistence are shared platform dependencies. Authorization scopes documents and notes by artifact; they are not separate databases.'),devops:fact('Source definition and standalone Node application can be downloaded. GitHub publication uses a reviewed file set and a new branch in an explicitly configured repository.'),endpoints:fact('Graduated server: /health, / and /data.json. No enterprise endpoint or secret copied into source.'),storage:fact(`Platform: ${app.documents.length} document objects and ${app.comments.length} notes. Full graduation archive includes their content; code-only GitHub publication excludes it.`),permissions:fact(`${claim.permissions} Docker build workers disable networking. Kubernetes build isolation depends on verified cluster policies; the controller holds job-management privileges.`)}
  };
}
export function validateAssurance(value){
  const keys=(v,allowed)=>{if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).some(k=>!allowed.includes(k))||allowed.some(k=>!Object.hasOwn(v,k)))throw new Error('Assurance record has missing or unknown fields');};
  keys(value,['arb','readiness','bom','components']);
  for(const [kind,list] of Object.entries(sections)){
    keys(value[kind],list.map(([key])=>key));
    for(const [key] of list){const item=value[kind][key];keys(item,['status','text','owner','evidence']);
      if(!['unknown','proposed','documented','not-applicable'].includes(item.status)||typeof item.text!=='string'||item.text.length>6000||typeof item.owner!=='string'||item.owner.length>120||!Array.isArray(item.evidence)||item.evidence.length>12||item.evidence.some(e=>typeof e!=='string'||e.length>500))throw new Error('Invalid assurance field '+kind+'.'+key);
      if(item.status!=='unknown'&&!item.text.trim())throw new Error('Explain the value or non-applicability for '+kind+'.'+key);
      if(item.status==='documented'&&(!item.evidence.length||item.owner==='Unassigned'||!item.owner.trim()))throw new Error('Documented claims require an owner and evidence reference');
    }
  }
  if(!Array.isArray(value.components)||value.components.length>50)throw new Error('Invalid component inventory');
  const seen=new Set();for(const c of value.components){keys(c,['id','name','category','version','license','owner','source','dependencies','status']);if(Object.values(c).some(v=>typeof v!=='string'||v.length>500)||!c.id||seen.has(c.id))throw new Error('Invalid or duplicate component');seen.add(c.id);}
  return structuredClone(value);
}
export function assuranceRecord(app){
  const authored=app.assurance||{revision:0,release:null,updatedAt:null,updatedBy:null,history:[],data:initialAssurance()};
  const result=app.release?.result;
  const claim=scriptClaim(result?.config||app.config);
  const data=structuredClone(authored.data),generated=generatedAssurance(app);
  for(const [kind,fields] of Object.entries(generated))Object.assign(data[kind],fields);
  const generatedComponents=[{id:'pac-node',name:'Node.js',category:'Graduated application runtime',version:'>=22; exact deployment version unknown',license:'Node.js license; bundled dependency licenses require scan',owner:'Deployment owner unassigned',source:'package.json and Dockerfile',dependencies:'OS image inventory unknown',status:'Generated requirement, deployment unverified'},{id:'pac-renderer',name:'Trusted HTML renderer',category:'Platform and generated application',version:'Bounded demo template',license:'Apache-2.0 platform source',owner:'PAC Manager maintainers',source:'definition.json and index.html',dependencies:'Node.js during compilation',status:'Generated from published definition'},{id:'pac-store',name:'App scoped JSON records',category:'Shared platform persistence',version:'Schema 1',license:'Apache-2.0 platform code',owner:'Workspace owner',source:'Platform state',dependencies:'Controller filesystem and backup policy',status:'Single writer; no HA'}];
  if(app.binding)generatedComponents.push({id:'pac-mock-claims',name:'Synthetic claims provider',category:'Explicit mock binding',version:'Demo fixture v1',license:'Apache-2.0 demo fixture',owner:'Workspace owner',source:'mock-claims.json',dependencies:'None external',status:'Mock only'});
  data.components=[...generatedComponents,...data.components.filter(c=>!c.id.startsWith('pac-'))];
  return {schemaVersion:'1.0',artifactId:app.id,title:result?.config.title||app.config.title,release:app.release?.number||null,definitionRevision:app.release?.revision||null,sourceDigest:result?.sourceDigest||null,generatedDigest:sha(JSON.stringify({generated,generatedComponents})),managedFields:Object.fromEntries(Object.entries(generated).map(([kind,fields])=>[kind,Object.keys(fields)])),
    recordRevision:authored.revision,authoredForRelease:authored.release,stale:authored.revision>0&&authored.release!==(app.release?.number||null),updatedAt:authored.updatedAt,updatedBy:authored.updatedBy,history:authored.history,releaseHistory:structuredClone(app.releaseHistory||[]),
    reviewStatus:'Pending independent review',facts:{scope:'Published PAC application and its platform dependencies; graduation is a standalone read-only snapshot.',definition:result?.config||null,buildMode:app.release?.mode||'No published build',checks:result?.checks||[],mockClaimsBound:app.binding,documentCount:app.documents.length,discussionCount:app.comments.length,artifactRuntime:`Trusted HTML renderer; ${claim.scripts}`,storage:'Shared single-writer JSON store with controller-enforced application access',graduatedRuntime:'Node.js >=22; exact deployed image digest not yet recorded',graduatedEndpoints:['GET /health public','GET / authenticated','GET /data.json authenticated'],graduatedIdentity:'New Basic Auth token supplied by deployer; workspace identities are not exported',dataHandling:'Uploaded content may contain sensitive data. Classification remains an owner review item.',serviceBindings:serviceBindings(app)},
    data};
}
export function completeness(record){const gaps=[];for(const [kind,list] of Object.entries(sections))for(const [key,title] of list){const item=record.data[kind][key];if(item.status==='unknown'||item.status==='proposed')gaps.push({kind,key,title,status:item.status});}return {missingOrProposed:gaps.length,total:Object.values(sections).reduce((n,list)=>n+list.length,0),stale:record.stale,reviewStatus:record.reviewStatus,gaps};}
export function saveAssurance(store,principal,id,input){
  const app=store.access(principal,id,true);if(input.revision!==(app.assurance?.revision||0))throw Object.assign(new Error('Assurance record changed. Reload before saving.'),{status:409});
  if(input.release!==(app.release?.number||null))throw Object.assign(new Error('Published release changed. Reload before saving.'),{status:409});
  const data=validateAssurance(input.data),at=new Date().toISOString(),revision=input.revision+1;
  app.assurance={revision,release:input.release,updatedAt:at,updatedBy:principal.label,data,history:[...(app.assurance?.history||[]),{revision,release:input.release,at,actor:principal.label,digest:sha(JSON.stringify(data))}].slice(-50)};
  store.audit(app,'assurance record updated '+revision,principal);store.save();return assuranceRecord(app);
}
export const authoringGuide=`Prepare an evidence-backed graduation dossier for the published application. Read the assurance schema and current record first. Work from the published definition and observed facts, and ask the owner for missing decisions. Update structured JSON using update_assurance with the record revision and release. Use unknown for missing information; proposed for recommendations; documented only with an owner and an evidence reference; not-applicable requires a rationale. Never invent review signoffs, tests, costs, recovery objectives or approvals. An evidence reference is a claim by the author, not verified test execution. Do not copy credentials, customer data, private reference documents or raw knowledge uploads into the dossier. Components must distinguish application dependencies from platform dependencies, include version/license/ownership/source, and mark unknowns explicitly. Document architecture/trust boundaries, security, DR, costs, operational readiness and inventory. Render ARB, readiness and BOM views on demand after saving; they all derive from the same record. Preparing or rendering documents does not approve an architecture or mark it production ready. GitHub publishing is a separate browser-owner action after reviewing the exact destination and file content.`;

export function reportMarkdown(record,kind){
  if(!sections[kind])throw new Error('Unknown report');
  const lines=[`# ${reportTitles[kind]}\n\n${record.title}`,`Release: ${record.release??'Unpublished'} · Record revision: ${record.recordRevision}`,`Review: ${record.reviewStatus}${record.stale?' — STALE: authored for an earlier release':''}`,`Source digest: ${record.sourceDigest||'Unavailable'}`,'Generated from structured assurance data. Documented means an author supplied evidence; it does not mean the platform verified or approved it.','## Observed platform facts',...Object.entries(record.facts).map(([key,v])=>`- ${key}: ${typeof v==='object'?JSON.stringify(v):v}`),'## Revision history',...record.history.map(h=>`- Revision ${h.revision} · release ${h.release} · ${h.at} · ${h.actor} · ${h.digest}`)];
  lines.push('## Application release history',...record.releaseHistory.map(h=>`- Release ${h.release} · ${h.at} · Changed fields: ${h.changedFields.join(', ')} · Source ${h.sourceDigest}`));
  for(const [key,title] of sections[kind]){const r=record.data[kind][key];lines.push(`## ${title}`,`Status: ${r.status} · Owner: ${r.owner||'Unassigned'}`,r.text||'Not yet supplied.',...r.evidence.map(e=>'Evidence reference: '+e));}
  if(kind==='bom'){lines.push('## Component inventory',...record.data.components.map(c=>`### ${c.name}\n\n`+Object.entries(c).map(([k,v])=>`- ${k}: ${v||'Unknown'}`).join('\n')));if(!record.data.components.length)lines.push('No authored inventory yet. Observed runtime: Node.js >=22 and trusted HTML/CSS; exact image versions and transitive OS packages require a deployment inventory scan. This operational BOM is not a complete SBOM.');}
  if(kind==='arb')lines.push('## Observed demo architecture','```mermaid\nflowchart TD\n A[Authoring client] -->|Authenticated MCP| B[PAC controller]\n U[Team browser] -->|Scoped session| B\n B -->|Bounded definition| C[Ephemeral builder]\n B --> D[App scoped JSON records]\n B --> E[Synthetic claims provider]\n B -->|Sandboxed HTML| U\n```','Trust boundaries: authoring client and browser are outside the controller. The builder receives a definition without data or secrets. Docker workers have no networking; Kubernetes requires independently verified namespace policy. Browser previews execute no scripts. This depicts the observed demo, not a proposed production deployment. Supply additional target and DR diagrams as evidence references.');
  return lines.join('\n\n')+'\n';
}
export function reportHtml(record,kind){
  const md=reportMarkdown(record,kind);const body=md.split('\n\n').map(p=>p.startsWith('### ')?'<h3>'+escape(p.slice(4))+'</h3>':p.startsWith('## ')?'<h2>'+escape(p.slice(3))+'</h2>':p.startsWith('# ')?'<h1>'+escape(p.slice(2))+'</h1>':'<p>'+escape(p)+'</p>').join('');
  const diagram=kind==='arb'?'<h2>Observed demo topology</h2><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 660 350" role="img" aria-label="Authoring client and team browser connect to the PAC controller. Controller invokes a build worker, app-scoped JSON records and a mock claims provider."><g fill="none" stroke="var(--pac-ink-muted,#617b68)" stroke-width="2"><path d="M150 65V110H290V150M510 65V110H370V150M330 200V245M330 245H110V280M330 245V280M330 245H550V280"/><rect x="220" y="125" width="220" height="100" rx="10" stroke-dasharray="5 5"/></g><g fill="var(--pac-canvas,#f1f5ee)" stroke="var(--pac-line,#b9c8ba)"><rect x="50" y="15" width="200" height="50" rx="5"/><rect x="410" y="15" width="200" height="50" rx="5"/><rect x="240" y="150" width="180" height="50" rx="5"/><rect x="20" y="280" width="180" height="50" rx="5"/><rect x="240" y="280" width="180" height="50" rx="5"/><rect x="460" y="280" width="180" height="50" rx="5"/></g><g text-anchor="middle" font-family="sans-serif" font-size="14" fill="var(--pac-ink,#203b32)"><text x="150" y="46">Authoring client</text><text x="510" y="46">Team browser</text><text x="330" y="181">PAC controller</text><text x="110" y="311">Build worker</text><text x="330" y="311">App scoped JSON</text><text x="550" y="311">Mock claims provider</text><text x="150" y="100" font-size="11">Authenticated MCP</text><text x="510" y="100" font-size="11">Scoped session and preview</text></g></svg><p>Lines show dependency and request relationships. The dashed outline identifies the controller trust boundary; it is not a claim of network enforcement. Builds use the mode recorded above. JSON records and mock claims are platform dependencies. Production and disaster recovery topologies still require design evidence.</p>':'';
  return '<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>'+escape(brand.t('product.name','PAC Manager'))+' · '+escape(reportTitles[kind])+'</title><style>:root{'+brand.cssVars().replace(/^:root\{|\}$/g,'')+'}</style><style>body{font:15px/1.65 system-ui,sans-serif;color:var(--pac-ink,#172d23);max-width:850px;margin:45px auto;padding:0 28px}h1{font-size:30px;color:#000}h2{font-size:19px;margin-top:30px;color:#000;border-bottom:1px solid #ddd;padding-bottom:7px}h3{font-size:16px;color:#000}p{white-space:pre-wrap;overflow-wrap:anywhere}svg{width:100%;height:auto;break-inside:avoid} @media print{body{margin:0;font-size:11pt}h2,h3{break-after:avoid}p{orphans:3;widows:3}@page{size:letter;margin:.75in}}</style>'+body+diagram+'</html>';
}
